// Auto-generated by scripts/set-env.js during build
export const environment = {
  production: true,
  supabaseUrl: 'https://euertyrqjpxeerirtars.supabase.co',
  supabaseKey: 'sb_publishable_cgG20CGLDSoWLz2I1pW7FQ_HNZpgwm-',
  storageBucket: 'portfolio-media'
};
