const fs = require('fs');
const path = require('path');

const supabaseUrl = process.env.SUPABASE_URL || 
                    process.env.PUBLIC_SUPABASE_URL || 
                    process.env.NEXT_PUBLIC_SUPABASE_URL || 
                    process.env.NG_APP_SUPABASE_URL || 
                    'https://euertyrqjpxeerirtars.supabase.co';

const supabaseKey = process.env.SUPABASE_ANON_KEY || 
                    process.env.SUPABASE_KEY || 
                    process.env.PUBLIC_SUPABASE_ANON_KEY || 
                    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 
                    process.env.NG_APP_SUPABASE_ANON_KEY || 
                    'sb_publishable_cgG20CGLDSoWLz2I1pW7FQ_HNZpgwm-';

const storageBucket = process.env.STORAGE_BUCKET || 'portfolio-media';

const envConfigFile = `// Auto-generated by scripts/set-env.js during build
export const environment = {
  production: true,
  supabaseUrl: '${supabaseUrl.trim()}',
  supabaseKey: '${supabaseKey.trim()}',
  storageBucket: '${storageBucket.trim()}'
};
`;

const envDir = path.join(__dirname, '../src/environments');
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

// Write to both environment.prod.ts and environment.ts during production build
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), envConfigFile);
fs.writeFileSync(path.join(envDir, 'environment.ts'), envConfigFile);

console.log('✅ Environment configuration injected successfully for Vercel/Production build:');
console.log('   - Supabase URL:', supabaseUrl !== 'YOUR_SUPABASE_URL' ? supabaseUrl : '(placeholder)');
console.log('   - Storage Bucket:', storageBucket);
